# Generated by Django 5.1 on 2024-08-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_quiz_answer_quiz_desc_quiz_number_quiz_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
