# Generated by Django 5.1 on 2024-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_hero_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='None', max_length=200)),
                ('section', models.TextField(default='None')),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.AddField(
            model_name='hero_day',
            name='event',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hero_day',
            name='event_desc',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='hero_day',
            name='person',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='hero_day',
            name='person_desc',
            field=models.TextField(default='None'),
        ),
    ]
