# Generated by Django 5.1 on 2024-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_day',
            name='img',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
